from .clinica_controller import ClinicaController
from .paciente_controller import PacienteController
from .profissional_controller import ProfissionalController
from .atendimento_controller import AtendimentoController
from .procedimento_controller import ProcedimentoController
from .pagamento_controller import PagamentoController
from .relatorios_controller import RelatoriosController
from .controlador_sistema import ControladorSistema
